[package]
name = "hivemind"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
async-nats = "0.39.0"
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
tracing = "0.1.41"
